# Generated by Django 5.2.9 on 2025-12-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_teachermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='exams.teachermessage'),
        ),
    ]
