# Generated by Django 5.2.9 on 2025-12-09 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('graded', 'Graded')], default='in_progress', max_length=20),
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='percentage',
        ),
    ]
