# Generated by Django 5.2.9 on 2025-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_studentexamattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
