# Generated by Django 5.2.9 on 2025-12-11 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_examattempt_marks_obtained_examattempt_passed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examattempt',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='submitted_at',
        ),
    ]
