# Generated by Django 5.2.9 on 2025-12-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_alter_examattempt_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentExamAttempt',
        ),
    ]
