# Generated by Django 5.2.9 on 2025-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_delete_studentexamattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
